### ISSUE TITLE
No internet after connection

### ISSUE THREAD

**Issue by pedosb** [joary/ufpa-vpn-mobile-config#1]
Hello,

I am trying to use the VPN, I imported it successfully, but when trying to turn on it asks for a certificate. I clicked in continue without one. It connects but then leaves me with no internet connection. Do you have any idea on what could be happening?

Thank you for this awesome project!

**Comment by pedosb** [comment]
Fortunately, the instructions in https://wiki.ctic.ufpa.br/index.php/VPN_no_Android worked.

**Comment by joary** [comment]
Thank you very much for the information, I updated the instructions for newcomers.
Closing the issue.
